#!/bin/bash

YEAR="$1"
DAY="$2"
TEMPLATE="$3"

COOKIE=$(cat ".cookie")

if [[ "$COOKIE" == "" ]]; then
  printf "COOKIE is not set inside .cookie. Please create a .cookie file with the cookie value from advent of code request headers. See readme.md for more details."
  exit 1
fi

mkdir -p "aoc-$YEAR/day-$DAY"

curl --cookie "$COOKIE" "https://adventofcode.com/$YEAR/day/$DAY" > "$DAY.html"
pandoc -f html -t commonmark "$DAY.html" > "aoc-$YEAR/day-$DAY/question_raw.md"
rm "$DAY.html"

curl --cookie "$COOKIE" "https://adventofcode.com/$YEAR/day/$DAY/input" \
  > "aoc-$YEAR/day-$DAY/input.txt"

if [[ "$TEMPLATE" == "go" ]]; then
  cp ./templates/go/*.go "aoc-$YEAR/day-$DAY/"
fi
